[[redirects]]
 from = "https://m.arborlifedesigns.com"
 to = "https://arborlifedesigns.com/contact"
 status = 200
 force = true

[[redirects]]
 from = "https://p.arborlifedesigns.com"
 to = "https://arborlifedesigns.com/payment"
 status = 200
 force = true
 
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200
  
[functions]
  node_bundler = "esbuild"